// FILM.TIMELINE: "HOMO CURIOSUS — origin". Owner: director. Plan: docs/storyboard.md. Rules: docs/art-bible.md.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps); a bar is 2 s; 14 bars = 28 s. Cuts sit on the 8th grid (0.25 s).
// Narration (locked, vo/assets/timing.json) leads: every cut and hit below was placed against the measured words.
(function () {
  'use strict';
  const FILM = window.FILM;

  FILM.TIMELINE = {
    title: 'WHY WE WONDER — origin',
    bpm: 120,
    duration: 28,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      { id: 'cave-hand', file: '01-cave-hand.js', start: 0, end: 2.75, mode: 'illustrated', title: 'A hand in the dark', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Torch-lit limestone cave wall, 67,800 years ago. A real human hand (cross-hatched skin, knuckle creases, nails) descends from the top-right in perspective and presses flat onto the wall on the G1 frame at T 2.25. Dust motes, flickering torch light, older faded stencils and claw marks on the rock. Camera creeps in.' },
      { id: 'ochre-breath', file: '02-ochre-breath.js', start: 2.75, end: 5.75, mode: 'illustrated', title: 'Breath and ochre', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Side-lit close shot of the same hand on the wall. From T 3.5 a cone of red ochre is blown from the lower left (thousands of droplets in flight with streaks, settling as a stipple halo on the rock). At T 5.0 the hand lifts away and reveals the negative stencil on G1; the fingers subtly narrow (the real Muna stencil was retouched claw-like). At T 5.25 the curiosity line ignites at the index fingertip.' },
      { id: 'question-wall', file: '03-question-wall.js', start: 5.75, end: 8.25, mode: 'schematic', title: 'A question on a wall', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Blueprint of the stencil (identical G1 outline in pale linework) with hidden systems revealed: calcite crust strata above it with a uranium-series sample core, a hematite (Fe2O3) crystal lattice inset, measurement brackets. The curiosity line leaves the index fingertip, sweeps up and curls into a giant "?" (G3) by T 6.875; the dot lands at T 7.0 and becomes a star (G4).' },
      { id: 'star-lines', file: '04-star-lines.js', start: 8.25, end: 11, mode: 'illustrated', title: 'Lines between the stars', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'An engraved celestial chart on ivory: the "?" dot is now a star at G4. The curiosity line hops star to star on the 8ths, drawing Orion; an engraved hunter figure (hatched) fades up behind; a planisphere with rotating rings, zodiac ticks and Latin labels surrounds it. At T 10.5 the outer ring locks into the G5 circle.' },
      { id: 'bronze-computer', file: '05-bronze-computer.js', start: 11, end: 13.75, mode: 'schematic', title: 'A computer of bronze', transitionIn: { kind: 'cut', dur: 0 },
        brief: '3D (Three.js in Remotion): the G5 ring becomes the Antikythera main wheel. Exploded, corroded-bronze gear train meshing; camera orbits from face-on to three-quarter. The pf scene draws the blueprint plate behind and the 2D annotation layer (tooth counts 223, 38, 127; dial spirals; bracket "c. 150 BC") as a separate overlay scene.' },
      { id: 'twelve-seconds', file: '06-twelve-seconds.js', start: 13.75, end: 16, mode: 'illustrated', title: 'Twelve seconds', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Kitty Hawk, 17 December 1903, as a dense ink illustration: the Wright Flyer (canard elevator, twin pushers, wing ribs and wires, Orville prone) leaves the launch rail at T 14.5 while Wilbur runs at the wingtip; sand dunes, wind-bent grass, a stopwatch arc annotation counting 0 to 12 s, a 120 ft bracket. The curiosity line is the flight path, exiting top right.' },
      { id: 'line-to-moon', file: '07-line-to-moon.js', start: 16, end: 18.75, mode: 'schematic', title: 'Follow the line to the Moon', transitionIn: { kind: 'cut', dur: 0 },
        brief: '3D (Three.js in Remotion): enormous scale change. The flight path keeps rising; the camera pulls back through the atmosphere to an ink-textured Earth and the curiosity line traces a free-return figure-8 to a hatched Moon, which lands on the G6 circle at T 18.25.' },
      { id: 'bigger-question', file: '08-bigger-question.js', start: 18.75, end: 21.75, mode: 'illustrated', title: 'Every answer, a bigger question', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A continuous Droste zoom on ivory engraving: the Moon (G6) is the dot of a "?" whose hook encloses an eye; the pupil is a cell; the nucleus coils into DNA; the DNA rung is a galaxy arm; the galaxy core is the next "?" dot. Each answer opens into a bigger question, zooming on the beat. Ends on a single line heading left at G7.' },
      { id: 'homo-curiosus', file: '09-homo-curiosus.js', start: 21.75, end: 24.25, mode: 'schematic', title: 'WHY WE WONDER', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Midnight navy. The curiosity line writes the wordmark in one continuous stroke of light (construction geometry, ruled baselines, compass arcs), HOMO at T 22.5 and CURIOSUS at T 23.125; small engraved vignettes from every earlier shot (hand, star, gear, flyer, Moon) orbit the word on the curiosity line.' },
      { id: 'stay-curious', file: '10-stay-curious.js', start: 24.25, end: 28, mode: 'illustrated', title: 'Stay curious', transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Back on the torch-lit cave wall: the ochre stencil on G1, now carrying the HOMO CURIOSUS mark. The line circles the hand once, writes "stay curious." in hand-ink beside it, then slips off frame toward the dark: the film loops to shot 1.' },
    ],
    cues: [
      { t: 0, kind: 'open' },
      { t: 2.25, kind: 'press' },
      { t: 2.75, kind: 'cut' },
      { t: 3.5, kind: 'breath' },
      { t: 5.0, kind: 'lift' },
      { t: 5.25, kind: 'ignite' },
      { t: 5.75, kind: 'cut' },
      { t: 6.375, kind: 'curl' },
      { t: 7.0, kind: 'dot' },
      { t: 8.25, kind: 'cut' },
      { t: 8.75, kind: 'star' },
      { t: 9.25, kind: 'star' },
      { t: 9.75, kind: 'star' },
      { t: 10.25, kind: 'star' },
      { t: 10.5, kind: 'lock' },
      { t: 11, kind: 'cut' },
      { t: 11.875, kind: 'gear' },
      { t: 13.25, kind: 'bronze' },
      { t: 13.75, kind: 'cut' },
      { t: 14.5, kind: 'liftoff' },
      { t: 15.5, kind: 'flew' },
      { t: 16, kind: 'cut' },
      { t: 18.25, kind: 'moon' },
      { t: 18.75, kind: 'cut' },
      { t: 19.5, kind: 'zoom' },
      { t: 20.25, kind: 'zoom' },
      { t: 21.0, kind: 'question' },
      { t: 21.75, kind: 'cut' },
      { t: 22.5, kind: 'homo' },
      { t: 23.125, kind: 'curiosus' },
      { t: 24.25, kind: 'cut' },
      { t: 24.75, kind: 'curious' },
      { t: 27.5, kind: 'out' },
    ],
  };
})();
