#!/usr/bin/env node
/* Writes MAP.md: every source file with its top-level definitions and the
   line each one starts on. Reading this one small file is enough to find
   anything in the project, instead of grepping the whole tree. */
const fs = require('fs'), path = require('path');
const SRC = path.join(__dirname, '..', 'src');
const OUT = path.join(__dirname, '..', 'MAP.md');

const DEF = /^(?:function\s+([A-Za-z_$][\w$]*)|var\s+([A-Za-z_$][\w$]*)\s*=|([A-Za-z_$][\w$.]*)\s*=\s*function|(SCREEN_BUILDERS|CUSTOM_TEX)\.([\w$]+)\s*=|(?:World|M4)\.prototype\.([\w$]+)\s*=)/;
const CALLS = /^\s*(?:CT|defMob|defBlock|defItem|recipe|R\.)\(/;

const files = fs.readdirSync(SRC).filter(f => f.endsWith('.js')).sort();
let out = ['# Code map', '',
  'Generated by `node tools/map.js` (the build runs it). One line per top-level',
  'definition: `name  file:line`. Find the file and line here, read only that',
  'slice, edit it, then `node tools/build.js` to regenerate `minecraft.html`.',
  '', '| file | lines | what is in it |', '| --- | ---: | --- |'];

const BLURB = {
  '00_s_core': 'maths, RNG, noise, small shared helpers',
  '01_s_blocks': 'the block registry — every block id and its properties',
  '02_s_biomes': 'biome table and climate lookup',
  '03_s_worldgen': 'terrain density, caves, ore placement',
  '04_s_features': 'trees, plants, decorations placed per chunk',
  '05_s_structures': 'villages, mineshafts, strongholds, temples, monuments',
  '10_tex_core': 'the pixel-art painting DSL and colour helpers',
  '11_tex_plants': 'plant and foliage tiles',
  '12_tex_custom': 'hand-painted block tiles',
  '13_tex_mobs': 'mob faces and hides',
  '20_glmath': 'matrix and vector maths (column-major)',
  '21_models': 'block model boxes for non-cube blocks',
  '22_mesher': 'chunk meshing — the three render passes',
  '30_world': 'chunk storage, lighting, the worker bridge',
  '40_gl': 'GL context, framebuffers, texture arrays',
  '41_shaders': 'terrain and entity shaders',
  '42_shaders2': 'post-processing shaders — composite, bloom, DOF, FXAA',
  '43_render': 'renderer state, settings, resize',
  '44_frame': 'the per-frame render order and post pass',
  '50_entities': 'entity draw buffer, the box emitter, body plans',
  '51_mobs': 'every mob definition and its animation',
  '52_ai': 'entity physics, pathing, aggro, damage',
  '53_effects': 'particles and weather',
  '60_items': 'the item registry',
  '62_itemtex': 'item icon painting',
  '63_recipes': 'crafting, smelting, brewing recipes',
  '64_loot': 'drop tables and chest loot',
  '70_player': 'the player controller — movement, mining, placing, damage',
  '71_viewmodel': 'first-person arms, held item models, swing animation',
  '80_ui_icons': 'HUD icon painting',
  '81_ui_core': 'HUD layout, slots, inventory click handling',
  '82_ui_screens': 'every full-screen UI',
  '90_blockentities': 'furnaces, chests, fluids, random ticks',
  '91_game': 'boot, the main loop, input, save and load, spawn',
  '92_redstone': 'redstone simulation',
  '93_bosses': 'dragon and wither fights',
  '94_achievements': 'achievements and the credits',
  '94b_player': 'player character models and skins',
  '95_net': 'multiplayer — relay, handshake, sync, chat, nameplates'
};

const detail = [];
for (const f of files) {
  const key = f.replace(/\.js$/, '');
  const lines = fs.readFileSync(path.join(SRC, f), 'utf8').split('\n');
  const names = [];
  lines.forEach((ln, i) => {
    const m = DEF.exec(ln);
    if (m) {
      const n = m[1] || m[2] || m[3] || (m[4] ? m[4] + '.' + m[5] : null) || m[6];
      if (n && n.length > 1) names.push(n + '  ' + f + ':' + (i + 1));
    }
  });
  out.push('| `src/' + f + '` | ' + lines.length + ' | ' + (BLURB[key] || '') + ' |');
  detail.push({ f, names });
}
out.push('', '## Definitions', '');
for (const d of detail) {
  if (!d.names.length) continue;
  out.push('### ' + d.f, '', '```');
  out.push(...d.names);
  out.push('```', '');
}
fs.writeFileSync(OUT, out.join('\n') + '\n');
console.log('MAP.md  ' + files.length + ' files, ' + detail.reduce((a, d) => a + d.names.length, 0) + ' definitions');
